substitutions:
  name: "esp-laser"
  friendly_name: "ESP Laser"

external_components:
  - source:
      type: git
      url: https://github.com/jerryhjones/kaufHA-common
      ref: multipleddp
    components: [ ddp ]
    refresh: always

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: jjones.esp8266laser
    version: "1.0.4"

dashboard_import:
    package_import_url: github://jerryhjones/esphome-templates/jjones-laser8266.yaml@1.0.4
    import_full_config: false # or true

esp8266:
  board: nodemcuv2

ddp:
debug:
button:
  - platform: restart
    name: "Restart"

text_sensor:
  - platform: debug
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: uptime
    name: "Uptime"

logger:
api:
ota:
wifi:
  ap:

captive_portal:

# Modify the PWM outputs for ESP8266
output:
  - platform: esp8266_pwm
    pin: D5 
    id: pwm_red
  - platform: esp8266_pwm
    pin: D6 
    id: pwm_green
  - platform: esp8266_pwm
    pin: D7 
    id: pwm_blue
  - platform: esp8266_pwm
    pin: D8 
    id: pwm_motor
  - platform: esp8266_pwm
    pin: D4
    id: 'null_output'

light:
  - platform: rgb
    name: "DDP Composite Laser"
    red: pwm_red
    green: pwm_green
    blue: pwm_blue
    effects:
      - ddp:
          timeout: 10s
          disable_gamma: true
  - platform: rgb
    name: "DDP Laser Rotation"
    red: pwm_motor
    green: null_output
    blue: null_output
    effects:
      - ddp:
          timeout: 10s
          disable_gamma: true
  - platform: monochromatic
    name: "Red Laser"
    output: pwm_red
    id: light_red
    default_transition_length: 1s
  - platform: monochromatic
    name: "Green Laser"
    output: pwm_green
    id: light_green
    default_transition_length: 1s
  - platform: monochromatic
    name: "Blue Laser"
    output: pwm_blue
    id: light_blue
    default_transition_length: 1s
  - platform: monochromatic
    name: "Rotation Speed"
    output: pwm_motor
    id: motor_speed
    default_transition_length: 0s