substitutions:
  name: "esp-light-thing"
  friendly_name: "ESP Light Thing"

external_components:
  - source:
      type: git
      url: https://github.com/jerryhjones/kaufHA-common
      ref: multipleddp
    components: [ ddp ]
    refresh: always

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: jjones.esp-light-thing
    version: "1.0.1"

dashboard_import:
    package_import_url: github://jerryhjones/esphome-templates/jjones-esp-light-thing.yaml@esp-light-thing-1.0.1
    import_full_config: true # or true

esp8266:
  board: nodemcuv2

ddp:
debug:
button:
  - platform: restart
    name: "Restart"

text_sensor:
  - platform: debug
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: uptime
    name: "Uptime"

logger:
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:

# Modify the PWM outputs for ESP8266
output:
  - platform: esp8266_pwm
    pin: D4 
    id: pwm_red
  - platform: esp8266_pwm
    pin: D2 
    id: pwm_green
  - platform: esp8266_pwm
    pin: D0 
    id: pwm_blue
  - platform: esp8266_pwm
    pin: D1
    id: pwm_white

stepper:
  - platform: uln2003
    id: my_stepper
    pin_a: D8
    pin_b: D7
    pin_c: D6
    pin_d: D5
    max_speed: 250 steps/s

    # Optional:
    acceleration: inf
    deceleration: inf

light:
  - platform: monochromatic
    name: "Red LED"
    output: pwm_red
    id: light_red
    default_transition_length: 1s
  - platform: monochromatic
    name: "Green LED"
    output: pwm_green
    id: light_green
    default_transition_length: 1s
  - platform: monochromatic
    name: "Blue LED"
    output: pwm_blue
    id: light_blue
    default_transition_length: 1s
  - platform: monochromatic
    name: "White LED"
    output: pwm_white
    id: light_white
    default_transition_length: 1s

number:
  - platform: template
    name: Stepper Control
    min_value: -100
    max_value: 100
    step: 1
    set_action:
      then:
        - stepper.set_target:
            id: my_stepper
            target: !lambda 'return x;'