# These substitutions allow the end user to override certain values
substitutions:
  name: "novo-flood-template2"
  friendly_name: "Novostella Template"

esphome:
  name: "${name}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: jerryhjones.novostella-flood-template
    version: "1.0"

bk72xx:
  board: generic-bk7231t-qfn32-tuya

# To be able to get logs from the device via serial and api.
logger:

web_server:
  port: 80
  include_internal: true

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://jerryhjones/esphome-templates/novostella-flood-template.yaml@main
  import_full_config: true # or true

wifi:
  ap:
    password: ""
  

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:
debug:
button:
  - platform: restart
    name: Restart

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

sensor:
  - platform: uptime
    name: Uptime

output:
  - platform: libretiny_pwm
    id: output_red
    pin: P24 # Correct
  - platform: libretiny_pwm
    id: output_blue
    pin: P26 # Correct
  - platform: libretiny_pwm
    id: output_green
    pin: P6

light:
  - platform: rgb
    id: light_rgb
    name: ${name}
    red: output_red
    green: output_green
    blue: output_blue
